// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dkxtdlltiqipohbeavgd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRreHRkbGx0aXFpcG9oYmVhdmdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MjY4MjgsImV4cCI6MjA2MDEwMjgyOH0.YS9FkBGcbkhi2OwW0vnnqghpnjPk75uXZESHXniOPB0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);